#!/bin/bash
os=$(uname)
args="--no-window-system --no-init-file --load $HOME/.magit/init.el"
prefix=
if [ "$#" -eq 1 ]; then
    cd $1
fi

if [ "$#" -eq 2 ]; then
    cd $1
    prefix="env SHA=$2"
fi

if [ $os == "Darwin" ]; then
  $prefix /Applications/Emacs.app/Contents/MacOS/Emacs $args
else
  $prefix emacs $args
fi
